import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { 
  Factory, 
  FileText, 
  Package, 
  DollarSign, 
  TrendingUp,
  Users,
  Key,
  Zap,
  CheckCircle2,
  Clock,
  Star,
  BookOpen,
  Target,
  ArrowRight,
  RefreshCw,
  Gift
} from 'lucide-react';

interface IPAsset {
  id: string;
  name: string;
  type: 'framework' | 'diagnostic' | 'scorecard' | 'playbook' | 'template';
  status: 'draft' | 'published' | 'licensed';
  source: string;
  price: number;
  salesCount: number;
  revenue: number;
  licensees: number;
  autoGenerated: boolean;
  lastUpdated: Date;
}

interface IPCandidate {
  id: string;
  insight: string;
  source: string;
  potentialValue: number;
  conversionReady: number;
  suggestedFormat: string;
}

export function IPFactoryEngine() {
  const [autoCapture, setAutoCapture] = useState(true);
  
  const [assets, setAssets] = useState<IPAsset[]>([
    {
      id: '1',
      name: 'The Revenue Velocity Framework',
      type: 'framework',
      status: 'licensed',
      source: 'Client work patterns',
      price: 497,
      salesCount: 84,
      revenue: 41748,
      licensees: 12,
      autoGenerated: true,
      lastUpdated: new Date(Date.now() - 86400000 * 7)
    },
    {
      id: '2',
      name: 'Pricing Power Diagnostic',
      type: 'diagnostic',
      status: 'published',
      source: 'Sales objections library',
      price: 197,
      salesCount: 156,
      revenue: 30732,
      licensees: 0,
      autoGenerated: true,
      lastUpdated: new Date(Date.now() - 86400000 * 3)
    },
    {
      id: '3',
      name: 'Client Quality Scorecard',
      type: 'scorecard',
      status: 'published',
      source: 'Client outcome data',
      price: 97,
      salesCount: 312,
      revenue: 30264,
      licensees: 0,
      autoGenerated: true,
      lastUpdated: new Date(Date.now() - 86400000 * 14)
    },
    {
      id: '4',
      name: 'High-Ticket Closing Playbook',
      type: 'playbook',
      status: 'licensed',
      source: 'DM conversation wins',
      price: 797,
      salesCount: 28,
      revenue: 22316,
      licensees: 5,
      autoGenerated: false,
      lastUpdated: new Date(Date.now() - 86400000 * 30)
    }
  ]);

  const [candidates, setCandidates] = useState<IPCandidate[]>([
    {
      id: '1',
      insight: 'Pattern detected: 7-step objection handling sequence with 82% close rate',
      source: 'Last 50 closed deals',
      potentialValue: 15000,
      conversionReady: 78,
      suggestedFormat: 'Playbook + Template Bundle'
    },
    {
      id: '2',
      insight: 'Discovery: Clients who complete intake diagnostic have 3.4x LTV',
      source: 'Client journey analysis',
      potentialValue: 8500,
      conversionReady: 65,
      suggestedFormat: 'Automated Diagnostic Tool'
    },
    {
      id: '3',
      insight: 'Framework emerging: 4-stage "Revenue Audit" process from consulting work',
      source: 'Service delivery patterns',
      potentialValue: 22000,
      conversionReady: 45,
      suggestedFormat: 'Licensable Framework'
    }
  ]);

  const stats = {
    totalIPAssets: assets.length,
    monthlyRevenue: 18420,
    lifetimeRevenue: assets.reduce((sum, a) => sum + a.revenue, 0),
    activeLicensees: assets.reduce((sum, a) => sum + a.licensees, 0),
    avgAssetValue: Math.round(assets.reduce((sum, a) => sum + a.revenue, 0) / assets.length),
    insightsDetected: 23
  };

  const getTypeIcon = (type: IPAsset['type']) => {
    switch (type) {
      case 'framework': return <Target className="w-4 h-4" />;
      case 'diagnostic': return <CheckCircle2 className="w-4 h-4" />;
      case 'scorecard': return <Star className="w-4 h-4" />;
      case 'playbook': return <BookOpen className="w-4 h-4" />;
      case 'template': return <FileText className="w-4 h-4" />;
    }
  };

  const getStatusColor = (status: IPAsset['status']) => {
    switch (status) {
      case 'draft': return 'bg-muted text-muted-foreground';
      case 'published': return 'bg-green-500/20 text-green-400';
      case 'licensed': return 'bg-primary/20 text-primary';
    }
  };

  return (
    <div className="h-full overflow-auto p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold gradient-text flex items-center gap-2">
            <Factory className="w-6 h-6" />
            IP Factory & Licensing Engine
          </h1>
          <p className="text-muted-foreground">Turn knowledge into sellable assets that generate sleep revenue</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-sm text-muted-foreground">Auto-Capture</span>
            <Switch checked={autoCapture} onCheckedChange={setAutoCapture} />
          </div>
          <Badge className="bg-green-500/20 text-green-400 text-lg px-4 py-2">
            ${stats.monthlyRevenue.toLocaleString()}/mo
          </Badge>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        <Card className="bg-card/50 border-border/50">
          <CardContent className="p-4 text-center">
            <Package className="w-5 h-5 mx-auto mb-1 text-primary" />
            <div className="text-2xl font-bold">{stats.totalIPAssets}</div>
            <div className="text-xs text-muted-foreground">IP Assets</div>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-green-500/20 to-emerald-500/10 border-green-500/30">
          <CardContent className="p-4 text-center">
            <DollarSign className="w-5 h-5 mx-auto mb-1 text-green-400" />
            <div className="text-2xl font-bold text-green-400">${stats.lifetimeRevenue.toLocaleString()}</div>
            <div className="text-xs text-muted-foreground">Lifetime Revenue</div>
          </CardContent>
        </Card>
        <Card className="bg-card/50 border-border/50">
          <CardContent className="p-4 text-center">
            <Key className="w-5 h-5 mx-auto mb-1 text-yellow-400" />
            <div className="text-2xl font-bold">{stats.activeLicensees}</div>
            <div className="text-xs text-muted-foreground">Active Licensees</div>
          </CardContent>
        </Card>
        <Card className="bg-card/50 border-border/50">
          <CardContent className="p-4 text-center">
            <TrendingUp className="w-5 h-5 mx-auto mb-1 text-blue-400" />
            <div className="text-2xl font-bold">${stats.avgAssetValue.toLocaleString()}</div>
            <div className="text-xs text-muted-foreground">Avg Asset Value</div>
          </CardContent>
        </Card>
        <Card className="bg-card/50 border-border/50">
          <CardContent className="p-4 text-center">
            <Zap className="w-5 h-5 mx-auto mb-1 text-orange-400" />
            <div className="text-2xl font-bold">{stats.insightsDetected}</div>
            <div className="text-xs text-muted-foreground">Insights Detected</div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="assets" className="space-y-4">
        <TabsList className="bg-muted/50">
          <TabsTrigger value="assets">Published Assets</TabsTrigger>
          <TabsTrigger value="candidates">IP Candidates</TabsTrigger>
          <TabsTrigger value="licensing">License Management</TabsTrigger>
          <TabsTrigger value="automation">Auto-Generation</TabsTrigger>
        </TabsList>

        <TabsContent value="assets" className="space-y-4">
          {assets.map((asset) => (
            <Card key={asset.id} className="bg-card/50 border-border/50">
              <CardContent className="p-4">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <div className="flex items-center gap-3 mb-1">
                      {getTypeIcon(asset.type)}
                      <h3 className="font-semibold">{asset.name}</h3>
                      <Badge className={getStatusColor(asset.status)}>
                        {asset.status}
                      </Badge>
                      {asset.autoGenerated && (
                        <Badge variant="outline" className="text-xs">
                          <Zap className="w-3 h-3 mr-1" />
                          Auto-generated
                        </Badge>
                      )}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      Source: {asset.source}
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-xl font-bold text-green-400">${asset.revenue.toLocaleString()}</div>
                    <div className="text-sm text-muted-foreground">total revenue</div>
                  </div>
                </div>

                <div className="grid grid-cols-4 gap-4 p-3 bg-muted/30 rounded-lg">
                  <div>
                    <div className="text-xs text-muted-foreground">Price</div>
                    <div className="font-bold">${asset.price}</div>
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">Sales</div>
                    <div className="font-bold">{asset.salesCount}</div>
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">Licensees</div>
                    <div className="font-bold">{asset.licensees > 0 ? asset.licensees : '-'}</div>
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">Updated</div>
                    <div className="font-bold">{Math.round((Date.now() - asset.lastUpdated.getTime()) / 86400000)}d ago</div>
                  </div>
                </div>

                <div className="flex justify-end gap-2 mt-4">
                  <Button variant="outline" size="sm">Edit</Button>
                  <Button variant="outline" size="sm">Analytics</Button>
                  {asset.status !== 'licensed' && (
                    <Button size="sm" className="bg-primary">
                      <Key className="w-4 h-4 mr-1" />
                      Enable Licensing
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </TabsContent>

        <TabsContent value="candidates" className="space-y-4">
          <Card className="bg-card/50 border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <RefreshCw className="w-5 h-5 text-yellow-400" />
                Detected IP Candidates
              </CardTitle>
              <CardDescription>
                The engine continuously scans your work for monetizable patterns
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {candidates.map((candidate) => (
                <div key={candidate.id} className="p-4 bg-muted/30 rounded-lg">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <div className="font-medium">{candidate.insight}</div>
                      <div className="text-sm text-muted-foreground mt-1">
                        Source: {candidate.source}
                      </div>
                    </div>
                    <Badge className="bg-primary/20 text-primary">
                      Est. ${candidate.potentialValue.toLocaleString()}
                    </Badge>
                  </div>

                  <div className="flex items-center justify-between mt-4">
                    <div className="flex items-center gap-4">
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Conversion Ready</div>
                        <div className="flex items-center gap-2">
                          <Progress value={candidate.conversionReady} className="w-24 h-2" />
                          <span className="text-sm font-bold">{candidate.conversionReady}%</span>
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Suggested Format</div>
                        <Badge variant="outline">{candidate.suggestedFormat}</Badge>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm">Dismiss</Button>
                      <Button size="sm" className="bg-primary">
                        <Package className="w-4 h-4 mr-1" />
                        Convert to Asset
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="licensing" className="space-y-4">
          <Card className="bg-card/50 border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Key className="w-5 h-5 text-yellow-400" />
                License Management
              </CardTitle>
              <CardDescription>
                Manage white-label licenses and recurring revenue
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div className="p-4 bg-gradient-to-br from-green-500/20 to-emerald-500/10 rounded-lg">
                  <div className="text-sm text-muted-foreground mb-1">Monthly License Revenue</div>
                  <div className="text-3xl font-bold text-green-400">$4,250</div>
                  <div className="text-sm text-muted-foreground">from 17 active licenses</div>
                </div>
                <div className="p-4 bg-muted/30 rounded-lg">
                  <div className="text-sm text-muted-foreground mb-1">License Renewal Rate</div>
                  <div className="text-3xl font-bold">94%</div>
                  <div className="text-sm text-muted-foreground">12-month average</div>
                </div>
              </div>

              {[
                { licensee: 'Growth Agency Co.', asset: 'Revenue Velocity Framework', monthly: 497, since: '8 months' },
                { licensee: 'Sales Mastery Inc.', asset: 'High-Ticket Closing Playbook', monthly: 797, since: '5 months' },
                { licensee: 'Consulting Pro LLC', asset: 'Revenue Velocity Framework', monthly: 497, since: '3 months' },
                { licensee: 'Scale Partners', asset: 'Pricing Power Diagnostic', monthly: 297, since: '2 months' }
              ].map((license, idx) => (
                <div key={idx} className="flex items-center justify-between p-4 bg-muted/30 rounded-lg">
                  <div>
                    <div className="font-medium">{license.licensee}</div>
                    <div className="text-sm text-muted-foreground">
                      {license.asset} • Active for {license.since}
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="text-right">
                      <div className="font-bold text-green-400">${license.monthly}/mo</div>
                      <div className="text-xs text-muted-foreground">auto-renews</div>
                    </div>
                    <Button variant="outline" size="sm">Manage</Button>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="automation" className="space-y-4">
          <Card className="bg-card/50 border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Zap className="w-5 h-5 text-yellow-400" />
                Auto-Generation Pipeline
              </CardTitle>
              <CardDescription>
                The engine automatically detects and packages IP from your daily work
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-4 gap-4 mb-6">
                {[
                  { source: 'Client Calls', scanned: 47, insights: 12 },
                  { source: 'Sales Conversations', scanned: 156, insights: 8 },
                  { source: 'Delivery Work', scanned: 23, insights: 5 },
                  { source: 'Support Tickets', scanned: 89, insights: 3 }
                ].map((source, idx) => (
                  <div key={idx} className="p-3 bg-muted/30 rounded-lg text-center">
                    <div className="text-sm font-medium">{source.source}</div>
                    <div className="text-2xl font-bold mt-1">{source.scanned}</div>
                    <div className="text-xs text-muted-foreground">scanned</div>
                    <div className="text-sm text-green-400 mt-1">{source.insights} insights</div>
                  </div>
                ))}
              </div>

              <div className="space-y-3">
                <h4 className="font-medium">Conversion Pipeline</h4>
                {[
                  { stage: 'Pattern Detection', count: 28, icon: <Target className="w-4 h-4" /> },
                  { stage: 'Insight Validation', count: 15, icon: <CheckCircle2 className="w-4 h-4" /> },
                  { stage: 'Asset Drafting', count: 8, icon: <FileText className="w-4 h-4" /> },
                  { stage: 'Ready for Review', count: 3, icon: <Gift className="w-4 h-4" /> }
                ].map((stage, idx) => (
                  <div key={idx} className="flex items-center gap-4">
                    <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center text-primary">
                      {stage.icon}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{stage.stage}</span>
                        <Badge variant="outline">{stage.count}</Badge>
                      </div>
                      <Progress value={(4 - idx) * 25} className="h-1.5 mt-1" />
                    </div>
                    {idx < 3 && <ArrowRight className="w-4 h-4 text-muted-foreground" />}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default IPFactoryEngine;
